nonsoolmate/NONSOOLMATE-SERVER

nonsoolmateServer/build.gradle
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/config/SecurityConfig.java

* #15 -> dev
* closed #15 
- CORS 설정을 위한 securityconfig 추가

[ADD] CORS 설정 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/redis/config/RedisConfig.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtTokenProvider.java

- fix/#22 -> dev
- closed #22 
- jwtTokenProvider 패키지 경로 수정
- RedisConfig Value 어노테이션 경로 수정
- 에러 없이 서버 잘 돌아갑니다!

[FIX] jwtTokenProvider 패키지 경로 수정 및 RedisConfig Value 어노테이션 경로 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/dto/response/MemberAuthResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/service/AuthService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MyController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/NameResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/TicketResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/nicknameResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/exception/MemberSuccessType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/service/MemberService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/NaverAuthService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java

- feat/#26 -> dev
- closed #26
- 내 정보 확인: 첨삭권 개수 조회 API 개발했습니다

[FEAT] 내 정보 확인: 첨삭권 개수 조회 API 개발

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/response/SelectUniversityResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java

- fix/#44 -> dev
- closed #44 
- 목표 대학 DTO 값 변경

[FIX] 목표대학 DTO 값 변경

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/repository/SelectUniversityRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java

- feat/#53 -> dev
- closed #53
- 목표 대학 "ㄱ-ㅎ"순 정렬 쿼리 작성

[FEAT] 목표 대학 "ㄱ-ㅎ"순 정렬 쿼리 작성

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/request/SelectUniversityRequestDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/controller/dto/request/CreateUniversityExamRequestDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/GlobalExceptionHandler.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/exception/CommonErrorType.java

- feat/#67 -> dev
- closed #67 
- MethodArgumentNotValidException 에러 핸들링
- RequestDTO에 유효성 검증 어노테이션 추가

[FEAT] MethodArgumentNotValidException 에러 핸들링 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtTokenProvider.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/filter/JwtAuthenticationFilter.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/filter/JwtExceptionFilter.java

- feat/#66 -> dev
- closed #66
- jwtException Filter 구현

[FEAT] jwtException Filter 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/response/SelectUniversityExamResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/dto/response/SelectUniversityExamsResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamSuccessType.java

- fix/#70 -> dev
- closed #70 
- 목표 대학 시험 리스트에서 시험 id가 universityId로 전달되는 것 수정했습니다
- 시험 보기: 시험 이름 & 제한 시간에서 SuccessType message를 대학 시험 정보 조회에 성공했습니다 로 수정했습니다
- 시험 보기: 시험 이름 & 제한 시간에서 /university/exam/info/{id} -> /university/exam/{id}/info 로 경로 수정했습니다
- API 명세서에 모두 반영

[FIX] dev test에 따른 수정 사항 (성은 API)

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/service/CloudFrontService.java

- feat/#72 -> dev
- closed #72 
- s3관련 한글파일 인코딩

[FIX] s3관련 한글파일 인코딩

---

.github/workflows/dev-CD.yml
.github/workflows/dev-CI.yml

[FIX] .pem 키파일 생성 여부 확인을 위한 CD script 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java

- add/#76 -> dev
- closed/#76
- cors 포트번호 변경

[ADD] cors 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/repository/SelectUniversityRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/UniversityRepository.java

- fix/#78 -> dev
- closed #78 
- 목표대학 조회 로직을 수정했습니다!
- 원래는 목표하지 않은 대학도 리턴되야 하는데, 목표한 대학만 리턴되는 문제를 발견하여 수정했습니다!

[FIX] 목표대학 조회 로직 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java

- fix/#80 -> dev
- closed #80
- 대학 시험 이름에 대학교 이름 + 시험 년도 포함되도록 수정했습니다
- 대학이름이 OO대 로 디비에 저장되어 있어 스크립트 수정하고 노션에 반영해두었습니다 + dev rds에서도 반영했습니다

[FIX] 대학 시험 이름에 대학교 이름 + 시험 년도 포함되도록 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/response/UniversityExamImageAndAnswerResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java

- feat/#82 -> dev
- closed #82
- 클라이언트 요구사항에 맞춰 문제이미지 & 해제PDF API에 학교 정보도 반환하도록 만들었습니다!

[FEAT] 해제: 문제이미지 & 해제PDF 학교 정보 반환 포함

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/controller/dto/response/UniversityExamRecordResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/service/UniversityExamRecordService.java

- feat/#84 -> dev
- closed #84
- 첨삭 PDF_해제PDF 시험정보 반환데이터 추가

[FEAT] 첨삭: 첨삭 PDF_해제PDF 시험정보 반환데이터 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MemberApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MyController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/SelectUniversityApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/SelectUniversityController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/controller/UniversityExamRecordApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/controller/UniversityExamRecordController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/swagger/config/SwaggerConfig.java

- feat/#88 -> dev
- closed #88 
- 스웨거 적용 및 security schema 적용

[FEAT]  API에 Swagger 설정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java

- feat/#93 -> dev
- closed #93
- 목표대학 로직 중 삭제 및 추가 로직을 메서드로 분리했습니다!

[REFACTOR] 목표대학 삭제 및 추가 로직 메서드 분리

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/entity/enums/PlatformType.java

- feat/#102 -> dev
- closed #102 
- 플랫폼 타입 검증 오류 수정

[FIX] 플랫폼 타입 검증 오류 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/exception/AuthExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/exception/UniversityExamRecordExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/service/UniversityExamRecordService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/error/AWSExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/service/S3Service.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/redis/repository/RedisTokenRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/exception/CommonErrorType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java

- fix/#101 -> dev
- closed #101

[FIX] API 명세서 점검 및 에러 메세지 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/universityExamRecord/service/UniversityExamRecordService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/service/CloudFrontService.java

- fix/#107 -> dev
- closed #107
- 유효시간 30초로 모두 통일했습니다!

[FIX] CloudFrontService에서 유효시간 30초로 통일

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/swagger/config/SwaggerConfig.java

- fix/#110 -> dev
- closed #110 
- prd swagger 요청시 CORS 에러가 발생하여 코드를 수정했습니다

[FIX] SwaggerConfig에 https 설정 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java

- fix/#115 -> dev
- closed #115

[FIX] corsFilter 삭제

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerProfileController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java

- fix/#117 -> dev
- closed #117 
- SecurityConfig 사용하지 않는 주석 삭제 및 서버 프로필 체크 URL 추가

[FIX] SecurityConfig 사용하지 않는 주석 삭제 및 서버 프로필 체크 URL 추가

---

nonsoolmateServer/.gitignore
nonsoolmateServer/build.gradle
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/DiscordAppender.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/DiscordWebHook.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/exception/ErrorLogAppenderException.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/exception/ErrorLogAppenderExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/Author.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/EmbedObject.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/Field.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/Footer.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/Image.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/JsonObject.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/discord/model/Thumbnail.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerProfileController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/GlobalExceptionHandler.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/logging/FilterConfig.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/logging/filter/CachedBodyRequestWrapper.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/logging/filter/CachedBodyServletInputStream.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/logging/filter/MDCFilter.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/logging/filter/ServletWrappingFilter.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/util/ApiCallUtil.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/util/HttpRequestUtil.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/util/MDCUtil.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/util/StringUtil.java
nonsoolmateServer/src/main/resources/console-appender.xml
nonsoolmateServer/src/main/resources/discord-appender.xml
nonsoolmateServer/src/main/resources/logback-dev.xml

- feat/#90 -> dev
- closed #90
- 디스코드 로깅 봇 기능을 추가했습니다!
- 회원가입 관련은 자고 일어나서 해보겠습니다..!

[FEAT] 디스코드 로깅 봇 붙이기

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/controller/AuthController.java

- feat/#119 -> dev
- closed #119
- 500 error 컨트롤러를 구현했습니다

[FEAT] error 컨트롤러 구현

---

nonsoolmateServer/src/main/resources/logback-dev.xml

- fix/#121 -> dev
- closed #121
- xml 수정

[FIX] xml dev로 수정

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/swagger/config/SwaggerConfig.java

- move/#126 -> dev
- closed #126
- 스웨어 폴더 위치 변경

[MOVE] 스웨거 폴더 위치 변경

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java

- fix/#133 -> dev
- closed #133
- 이전에 생성한 UniversityExamEntity 내의 getUnviersityExamFullName 메서드를 마이 페이지: 대학별 시험 리스트 조회 API에 적용하지 않았어서 수정했습니다

[FIX] getUniversityExamName -> getUniversityExamFullName 변경

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/UniversityExam.java

- fix/#135 -> dev
- closed #135
- 기디 요청에 따라 목표 대학 리스트 조회에서는 시험 이름에서 대학 이름이 제외되도록 수정합니다

[FIX] 목표 대학 리스트 조회에서는 시험 이름에서 대학 이름이 제외되도록 수정

---

README.md

[DOCS] Key Features 추가
